# Generated by Django 2.1.2 on 2020-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tel', models.CharField(default=False, max_length=15)),
                ('address1', models.CharField(default=False, max_length=100)),
                ('address2', models.CharField(default=False, max_length=100)),
                ('name', models.CharField(default=False, max_length=50)),
                ('latitude', models.CharField(default=False, max_length=20)),
                ('longitude', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('store', models.CharField(default=False, max_length=10)),
                ('user', models.CharField(default=False, max_length=10)),
                ('score', models.CharField(default=False, max_length=10)),
                ('content', models.CharField(max_length=500, null=True)),
                ('reg_time', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('latitude', models.FloatField(max_length=10, null=True)),
                ('longitude', models.FloatField(max_length=10, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
